# Name of this GitHub Actions workflow.
name: Semgrep-Sarif

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches if there are changes to .github/workflows/semgrep.yml:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep-sarif.yml
  # Schedule the CI job (this method uses cron syntax):
  # schedule:
    # - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    # # It is recommended to change the schedule to a random time.

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source
      - uses: actions/checkout@v4

      # Run Semgrep and output SARIF file
      - run: semgrep ci --sarif --sarif-output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Upload the SARIF file as an artifact
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sarif
          path: semgrep.sarif